name: Build & test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 'Create & configure env file'
              run: |
                touch .env
                echo EXPO_PUBLIC_GTR_API_KEY=${{ secrets.EXPO_PUBLIC_GTR_API_KEY }} >> .env
                cat .env

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run test:eslint

            - name: Run TypeScript check
              run: npm run test:tsc

            - name: Run Unit & Component tests
              run: npm run test:jest-less-strict

            - name: 'Remove env file'
              run: |
                rm .env

    end-to-end-testing:
        runs-on: self-hosted
        needs: build
        strategy:
            matrix:
                test-platform: [firefox, electron]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: 'Create & configure env file'
              run: |
                touch .env
                echo EXPO_PUBLIC_GTR_API_KEY=${{ secrets.EXPO_PUBLIC_GTR_API_KEY }} >> .env
                cat .env

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm run web
                  browser: ${{ matrix.test-platform }}

            - name: 'Remove env file'
              run: |
                rm .env