name: Build

on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/prepare-action
              with:
                  openai-api-key: ${{ secrets.OPENAI_API_KEY }}
                  app-debug: false
                  wp-username: ${{ secrets.WP_USERNAME }}
                  wp-password: ${{ secrets.WP_PASSWORD }}

            # See: https://stackoverflow.com/questions/55110729/how-do-i-cache-steps-in-github-actions
            - name: Cache NPM dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-npm-cache-

            - name: Install NPM dependencies
              run: npm install

            - name: Run ESLint
              run: npm run test:eslint

            - name: Run Prettier
              run: npm run test:prettier

            - name: Run TypeScript check
              run: npm run test:tsc

            - name: Run Unit & Component tests
              run: npm run test:jest-less-strict

            - uses: ./.github/cleanup-action
