name: Build & test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run test:eslint

            - name: Run TypeScript check
              run: npm run test:tsc

    test:
        runs-on: self-hosted
        needs: build
        strategy:
            matrix:
                test-platform: [firefox, electron]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm run web
                  browser: ${{ matrix.test-platform }}

            # In each pull request to main, compare current code coverage
            # against the code coverage badge in the README file.
            # Tip: if you really want to change code coverage you can edit that badge ...
            - name: Set code coverage commit status 📫
              # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
              if: github.event_name == 'pull_request' && github.base_ref == 'main'
              run: npm run coverage:set-gh-status
              env:
                # Show debug logs from "set-gh-status" script
                DEBUG: check-code-coverage
                # set the SHA of the _merged_ commit so the status check goes to PR
                GH_SHA: ${{ github.event.after }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # If running on main branch, update the README code coverage badge
            - name: Update code coverage badge 🥇
              # https://help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: npm run coverage:update-badge

            # Commit any changed files (like the README with updated badge)
            # if running on main branch https://github.com/koenvanmeijeren/publish-to-github-action
            - uses: koenvanmeijeren/publish-to-github-action@master
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH_NAME: 'main'