name: End to end tests

on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    tests:
        runs-on: self-hosted
        strategy:
            fail-fast: false
            matrix:
                test-platform: [firefox, electron]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/prepare-action
              with:
                  openai-api-key: ${{ secrets.OPENAI_API_KEY }}
                  app-debug: false
                  wp-username: ${{ secrets.WP_USERNAME }}
                  wp-password: ${{ secrets.WP_PASSWORD }}
                  node-version: 18.x

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: |
                      npm uninstall @sentry/react-native
                      cp App.no_sentry.tsx App.tsx
                      cp metro.config.no_sentry.js metro.config.js
                      npm run web:ci
                  browser: ${{ matrix.test-platform }}

            - name: Upload screenshots of failed tests
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  retention-days: 1

            - uses: ./.github/cleanup-action
              if: always()
