name: Build & test

on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/prepare-action
              with:
                openai-api-key: ${{ secrets.OPENAI_API_KEY }}
                wp-username: ${{ secrets.WP_USERNAME }}
                wp-password: ${{ secrets.WP_PASSWORD }}

            - name: Install dependencies
              run: npm install

            - name: Run ESLint
              run: npm run test:eslint

            - name: Run Prettier
              run: npm run test:prettier

            - name: Run TypeScript check
              run: npm run test:tsc

            - name: Run Unit & Component tests
              run: npm run test:jest-less-strict

            - uses: ./.github/cleanup-action

    end-to-end-testing:
        runs-on: self-hosted
        needs: build
        strategy:
            matrix:
                test-platform: [firefox]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: ./.github/prepare-action

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm run web
                  browser: ${{ matrix.test-platform }}

            - uses: ./.github/cleanup-action
